##-*-docker-image-name: :"aot-java"-*-
## AoT
#
#Version 1
FROM glassfish:latest
MAINTAINER jason.ng "ywn202@nyu.edu"
COPY ~/archemy.ear /
#COPY start.sh /
EXPOSE 8080
EXPOSE 4848
#ENTRYPOINT["/start.sh"]

